---
version: "3"
services:
 devopsdb:
   container_name: devopsdb
   image: bindulatha99/dbimage:v1
   ports:
     - "3306:3306"

 application:
   image: bindulatha99/appimage:v1
   container_name: containerapp
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
